### ISSUE TITLE
AppLovin not working?

### ISSUE THREAD

**Issue by gyorgygabor** [AppLovin/Android-Demo-App#1]
Hi,

I am trying out this demo app and I`m getting always an error message like: "Interstitial not ready for display. Please check SDK key or internet connection" or "Interstitial failed to load with error code 204".

I have added the sdk key correctly from the https://applovin.com/integration#androidIntegration.
My internet connection is in right.
I am using the latest sdk(6.1.4), Android Studio 1.4 and I am testing on a Samsung Galaxy Core Prime with Android 5.1.1.

Could you please help me?

Regards,
Gabor

**Comment by sdk-build-server** [comment]
Hi there,
Code 204 is what we call a "no-fill", which basically means that our server didn't have any ads for this specific placement. It can occur due to your frequency cap settings, but can also occur if your app is too new or we haven't seen enough users yet to know what to show. Since this is a demo app, it's a plausible scenario. An easy way to get around that is to enable "Test Mode" on our website, (under "Manage Apps"), which will guarantee we serve you a test ad. It's just the AppLovin logo if memory serves, but behaves identically to a real ad in the wild.
Sent from my iPhone




On Thu, Nov 26, 2015 at 10:57 PM -0800, "gyorgygabor" <notifications@github.com> wrote:












Hi,



I am trying out this demo app and I`m getting always an error message like: "Interstitial not ready for display. Please check SDK key or internet connection" or "Interstitial failed to load with error code 204".



I have added the sdk key correctly from the https://applovin.com/integration#androidIntegration

Im using the latest sdk(6.1.4), Android Studio 1.4 and Im testing on a Samsung Galaxy Core Prime with Android 5.1.1.



Could you please help me?



Regards,

Gabor
